### PR TITLE
Fix errorcode events missingfields

### PR DESCRIPTION
**Pull request by bingzhang**

### CODE REVIEW

**Comment by sandeep-ps** [comment]
@bingzhang, Could you please look into this PR when you get a chance? I had left some comments earlier. Thanks.

**Comment by bingzhang** [comment]
> @bingzhang, this PR is for this issue (#94), right? If so, I think the issue mentioned is different. It's about returning Bad Request error when doing POST / PUT.

it returns 400 when the request is bad (parameters are wrong).

**Comment by sandeep-ps** [comment]
@bingzhang, In that case, could you please create an issue and reference it in the CHANGELOG. Also, please resolve the merge conflicts. Thanks.

**Comment by bingzhang** [comment]
close this. and made another pr https://github.com/rokwire/rokwire-building-blocks-api/pull/575/files

**Pull request closed without merging**
