### PR TITLE
1021 remove empty env var

### LINKED ISSUE #1021: Remove empty env var pairs in catalog
### Description
If both the key and value of an environment variable is empty, do not save that as an env variable pair. 
Currently the empty fields are saved and it appears as empty fields in capability view page.

Screen Shot 2022-09-22 at 1 59 36 PM

### Acceptance Criteria
Empty env variable are redacted / not saved.

### PR DESCRIPTION
**Pull request by minump**
## Description
Checks if environment variable key and value pairs are empty before setting the environment variable in a Capability.
The env var pairs are set only if either key or value is non-empty.

**Fixes #1021**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Please get the latest changes from develop.

**Comment by sandeep-ps** [comment]
Could you please change the behavior as follows: 
1. When both fields are empty, you can ignore them from being saved. 

I will create a follow-up feature to make the key a required field if an environment variable row is present. It wouldn't make sense to have the key as the empty string, while there may be a reason to put the value as empty. The user will need to use the delete environment variable button to remove it if they accidentally add an environment variable row. What do you think about this?

**Comment by sandeep-ps** [comment]
Please ignore this message above: https://github.com/rokwire/rokwire-building-blocks-api/pull/1023#issuecomment-1265966940. I will think a little bit more and update.

**Comment by sandeep-ps** [comment]
Hi, @minump, I think it may be better to pause development on this feature until the delete environment variable PR gets merged.

Then, we can make the key a required field if an environment variable row is present, as it wouldn't make sense to have the key as the empty string, while there may be a reason to put the value as empty. The user can use the delete environment variable button to remove the row if they accidentally add an environment variable row in the form. What do you think about this?

**Comment by minump** [comment]
Closing this PR as the requirements have been changed.

**Pull request closed without merging**
