### PR TITLE
Make catalog pages more human readable format

### LINKED ISSUE #908: [TASK] Make contribution's person and organization order consistent.
### Description
In contribution details page, the Person and Organization details starts from affiliation and address fields. I think it is reading the field list in reverse order. Maybe its better to display the first name, last name and middle name and then list the details.

### PR DESCRIPTION
**Pull request by ywkim312**
## Description
_Please provide a summary of the pull request and the issue it fixes. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Fixes #908 #909 #914 #915**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Removing PR from GitHub project.

**Comment by sandeep-ps** [comment]
Hi, @ywkim312, Creating contributions seems to be working fine, but editing the Contrbution results in the person/organization details getting removed. Please look into this when you get a chance. Thanks.

**Comment by sandeep-ps** [comment]
This is the error I'm seeing in the logs.

```
    return self.view_functions[rule.endpoint](**req.view_args)
  File "rokwire-building-blocks-api/contributions/catalog/controllers/auth.py", line 25, in wrapped_view
    return view(**kwargs)
  File "rokwire-building-blocks-api/contributions/catalog/controllers/contribute.py", line 227, in contribution_edit
    if username in the_json_res["contributionAdmins"]:
KeyError: 'contributionAdmins'

```

**Comment by ywkim312** [comment]
> This is the error I'm seeing in the logs.
> 
> ```
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "rokwire-building-blocks-api/contributions/catalog/controllers/auth.py", line 25, in wrapped_view
>     return view(**kwargs)
>   File "rokwire-building-blocks-api/contributions/catalog/controllers/contribute.py", line 227, in contribution_edit
>     if username in the_json_res["contributionAdmins"]:
> KeyError: 'contributionAdmins'
> ```

Hmm this is an error that usually comes out when I tried to edit configuration but the actual contribution get removed from the db. For example, I created the new contribution in the browser, but removed the contribution record from the db but browser still has the contribution records on the screen, then I click the edit contribution button....

**Comment by ywkim312** [comment]
> Hi, @ywkim312, Creating contributions seems to be working fine, but editing the Contrbution results in the person/organization details getting removed. Please look into this when you get a chance. Thanks.

hmm I can't replicate it.

**Comment by sandeep-ps** [comment]
After little more debugging with Yongwook, we think the above error is not related to this PR. The issue has been added to https://github.com/rokwire/rokwire-building-blocks-api/issues/922

**Review by sandeep-ps — APPROVED** [review]

**Pull request merged**
