### PR TITLE
Release/1.19.0

### LINKED ISSUE #1139: [TASK] Release Building Blocks 1.19.0
### Description
_Please provide a detailed description of the issue._
_Example: As a (user or developer), I want to be able to (feature or function) so that (reason to implement)._

### Acceptance Criteria
_Please describe what it means for this issue to be considered complete._

### PR DESCRIPTION
**Pull request by sandeep-ps**
## Description
Release 1.19.0
Will be requesting for deployment for EventsBB only
Eventhough there are changes for other building blocks, others building blocks like AppConfig and Contributions and Catalog BB will be deployed later.

**Fixes #1139**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
@bingzhang @sandeep-ps  requesting review.

**Comment by sandeep-ps** [comment]
Tested the Events BB, and it looks good. I cannot approve this PR as I had initially created it, but you can consider it my approval. We can move forward with Events BB. Other BB testing can be done later before we request deployment for those sometime in the future.

**Comment by minump** [comment]
@bingzhang Awaiting your feedback. Looking to merge and deploy tomorrow.

**Comment by sandeep-ps** [comment]
@bingzhang, Could you please take a look at this PR soon? We want to move forward with the Events BB release and deployment. Thanks.

**Review by bingzhang — APPROVED** [review]

**Comment by bingzhang** [comment]
> @bingzhang, Could you please take a look at this PR soon? We want to move forward with the Events BB release and deployment. Thanks.

Looks good to me. Approved.

**Comment by minump** [comment]
Proceeding with deployment

**Pull request merged**
