### PR TITLE
989 arrange environment variables single line

### LINKED ISSUE #989: [FEATURE] Arrange the environment variables in a single line
Have the environment variable key and value input field in one line two column fashion. 
On the right side of the value field, there should be an eye icon for visibility toggle.

### PR DESCRIPTION
**Pull request by minump**
## Description
Environment key value pair form input fields is in one line. Styling for the element id's are present in style.css.

**Fixes #989**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
converting to draft as data deletion endpoint also needs to be modified in two fields and one line.

**Comment by minump** [comment]
updated data deletion endpoint fields. ready for review.

**Comment by minump** [comment]
Changing to draft.
Add 2 space between value input field and eye icon.
Add a <br> after the env var key value pair line.

**Comment by minump** [comment]
updated styling.
ready for review.

**Comment by sandeep-ps** [comment]
A few comments:
1. Please align the "Add environment variables" button with the start of the environment variable name text box. It looks slightly off. 
image
2. After adding the first new line, the button alignment changes. Please make this consistent like in the screenshot before (after fixing the alignment):
image
3. Please add consistent spacing between new lines of environment variables:
image

**Comment by sandeep-ps** [comment]
Other changes related to making this displayed in a single line look good to me. Thanks.

**Comment by minump** [comment]
> A few comments:
> 
> 1. Please align the "Add environment variables" button with the start of the environment variable name text box. It looks slightly off.
> 
> image
> 
> 2. After adding the first new line, the button alignment changes. Please make this consistent like in the screenshot before (after fixing the alignment):
> image
> 
> 3. When adding a new contribution, please add consistent spacing between new lines of environment variables:
> image

3. Is resolved.
About 1 and 2, tried various styling. but unable to rectify the issue.

**Comment by minump** [comment]
button placement and styling messed up. 
converting to draft.

**Comment by minump** [comment]
Closing this PR as another [PR](https://github.com/rokwire/rokwire-building-blocks-api/pull/1011) is created for the same issue

**Pull request closed without merging**
