### PR TITLE
1176 task release 1.20.0 for eventsBB

### LINKED ISSUE #1176: [TASK] Release 1.20.0
### Description
Release version 1.20.0

### Acceptance Criteria
Release PR created, reviewed, and merged to the master branch, tagged on the master branch, and deployment requested.

### PR DESCRIPTION
**Pull request by minump**
## Description
Release 1.20.0.
Issue [#1150](https://github.com/rokwire/rokwire-building-blocks-api/issues/1150) was not released in v 1.19.0. Added the event category update to v1.20.0. Only eventsBB changes are done. No other BB yaml file version is updated.

**Fixes #1176**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
Tested in local. GET localhost:9000/events/categories responds with categories list and subcategories as expected.
```
[
    {
        "category": "Big 10 Athletics",
        "subcategories": [
            "Baseball",
            "Men's Basketball",
            "Men's Cross Country",
            "Football",
            "Men's Golf",
            "Men's Gymnastics",
            "Men's Tennis",
            "Men's Track Field",
            "Wrestling",
            "Women's Basketball",
            "Women's Cross Country",
            "Women's Golf",
            "Women's Gymnastics",
            "Women's Soccer",
            "Softball",
            "Swim Dive",
            "Women's Tennis",
            "Women's Track Field",
            "Volleyball"
        ]
    },
    {
        "category": "Campus Visits"
    },
    {
        "category": "Career Development"
    },
    {
        "category": "Ceremonies & Services"
    },
    {
        "category": "Club Athletics"
    },
    {
        "category": "Conferences & Workshops"
    },
    {
        "category": "Exhibits"
    },
    {
        "category": "Festivals & Celebrations"
    },
    {
        "category": "Film Screenings"
    },
    {
        "category": "Performances"
    },
    {
        "category": "Receptions & Open House Events"
    },
    {
        "category": "Recreation, Health & Fitness",
        "subcategories": [
            "Group Fitness",
            "Aquatics",
            "Ice Skating",
            "Personal Training",
            "Student Wellness",
            "Adventure Rec",
            "Summer Camp"
        ]
    },
    {
        "category": "Social & Informal Events"
    },
    {
        "category": "Speakers & Seminars"
    }
]
```
Ready for review.

**Comment by minump** [comment]
Proceeding with dev deployment

**Comment by sandeep-ps** [comment]
Thanks, @minump.

@bingzhang, Could you please test the below request in the DEV instance?

```
http://api-dev.rokwire.illinois.edu/events?startDate.lte=2023-09-12T14:19:02&endDate.gte=2023-09-06T14:19:02&targetAudience=faculty&targetAudience=staff&category=Receptions%20&%20Open%20House%20Events
```
The primary thing to test is the categories part -> `category=Receptions%20&%20Open%20House%20Events`

I think there should be some events under this category, but 0 are being returned. Please test this locally by changing some event data (if needed). This and other similar requests with ampersand in category need to succeed to be backward compatible with Illinois app 4.0. Thanks.

**Comment by bingzhang** [comment]
> Thanks, @minump.
> 
> @bingzhang, Could you please test the below request in the DEV instance?
> 
> ```
> http://api-dev.rokwire.illinois.edu/events?startDate.lte=2023-09-12T14:19:02&endDate.gte=2023-09-06T14:19:02&targetAudience=faculty&targetAudience=staff&category=Receptions%20&%20Open%20House%20Events
> ```
> 
> The primary thing to test is the categories part -> `category=Receptions%20&%20Open%20House%20Events`
> 
> I think there should be some events under this category, but 0 are being returned. Please test this locally by changing some event data (if needed). This and other similar requests with ampersand in category need to succeed to be backward compatible with Illinois app 4.0. Thanks.

this request has wrong url encoding. there is `&`. If you use the below one it works.

Receptions%20%26%20Open%20House%20Events

**Comment by minump** [comment]
Tested in local.
```
curl --location 'http://localhost:9000/events?category=Recreation%2C%20Health%20%26%20Fitness' \
--header 'ROKWIRE-API-KEY: key'
```
gives expected response.

**Review by sandeep-ps — APPROVED** [review]
Postman tests succeeded locally. Approving.

**Review by bingzhang — APPROVED** [review]

**Comment by minump** [comment]
Merging PR. 
Will proceed with release deployment to dev and request for deployment to TEST and PROD.

**Pull request merged**
