### PR TITLE
814 create source repo url required conditionally

### LINKED ISSUE #814: [TASK] Create Soure Repo url to required if the source is opensource in catalog
In Contribution and Catalog's capability, there is an entry named isOpenSource. If this is True, then the apiDocUrl should be required one. Try to implement this.

### Acceptance Criteria
The yaml should contain the ability of making the apiDocUrl to be required or not based on the value of isOpenSource and should be working in the actual deployment.

### PR DESCRIPTION
**Pull request by minump**
## Description
In Contribution Catalog's 'Add a Capability' form, there is a radio button 'Is the Code Open Sourced?'. The field 'Source repo URL' should be displayed if the radio button value is 'yes'.
Fixed this by making source repo url field as hidden, and creating a js function which displays the field on click of button.

**Fixes #814**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [ ] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
This display's source repo URL field if 'yes' radio button is selected for 'Is code open sourced'. The 'source repo URL' field does not hide if radio button is changed to 'no' value. Unsure if this needs to be a functionality as well.

**Comment by minump** [comment]
> This display's source repo URL field if 'yes' radio button is selected for 'Is code open sourced'. The 'source repo URL' field does not hide if radio button is changed to 'no' value. Unsure if this needs to be a functionality as well.

SourceRepo URL should be hidden when radio button is "no" value. Use the onclick javascipt value to check and display.

**Comment by minump** [comment]
Converted to draft as source url needs another UI change.

**Comment by minump** [comment]
UI changes done for Source repo URL field in catalog. Request to review.

**Comment by sandeep-ps** [comment]
@minump, Could you please resolve the new merge conflicts in CHANGELOG? Thanks.

**Comment by sandeep-ps** [comment]
From Contributions BB, After I posted a Contribution with a sourceRepoUrl, in the GET, it's showing up as null. @ywkim312, could you please look into this when you get a chance?

**Comment by ywkim312** [comment]
> From Contributions BB, After I posted a Contribution with a sourceRepoUrl, in the GET, it's showing up as null. @ywkim312, could you please look into this when you get a chance?

will do

**Comment by ywkim312** [comment]
I have pushed the codes for inserting Source Repo Url in the POST. However, when editing the capability, the source repo url is not automatically showing. To see it, you have to check Is Open Source field on and off. @minump Can you fix this? Also, it has an error in editing as well caused from some mandatory keys are empty like Talent's talent name or something like that. This should be fixed as well.

**Comment by ywkim312** [comment]
> From Contributions BB, After I posted a Contribution with a sourceRepoUrl, in the GET, it's showing up as null. @ywkim312, could you please look into this when you get a chance?

pushed the code but still needs to do some more work. I posted those in another comment

**Comment by minump** [comment]
> I have pushed the codes for inserting Source Repo Url in the POST. However, when editing the capability, the source repo url is not automatically showing. To see it, you have to check Is Open Source field on and off. @minump Can you fix this? Also, it has an error in editing as well caused from some mandatory keys are empty like Talent's talent name or something like that. This should be fixed as well.

pushed code to fix the toggle of the textbox in the edit page. Also did a hotfix for the talent_name field. Yet to fix the retrieving of content of the sourceRepoUrl field in the edit page.

**Comment by sandeep-ps** [comment]
When I set "Is open source?" to "yes" and when viewing the contribution, it's showing as False in the Contribution BB database. Maybe using debug mode, please check that the POST request body is correct. Thanks.

**Comment by minump** [comment]
> When I set "Is open source?" to "yes" and when viewing the contribution, it's showing as False in the Contribution BB database. Maybe using debug mode, please check that the POST request body is correct. Thanks.

Fixed the isOpenSource value bug.

**Comment by ywkim312** [comment]
Maybe you haven't had a chance to work on it yet. The source repo url box in edit page still doesn't show when the open source is 'yes'

**Comment by sandeep-ps** [comment]
Hi, @minump, 

In the following scenario, there is an issue. Create a Contribution with `Is Code Open Source?` set to `True` and add a repo URL. Then, edit the contribution and change it to `False`. Now, the boolean field has changed its value, but the repo URL still contains the old value. I think it needs to be reset to null. The issue maybe with the update request to Contributions BB as the data in the backend seems to have not changed. Please look into this. Thanks.

**Comment by sandeep-ps** [comment]
> 



> Hi, @minump,
> 
> In the following scenario, there is an issue. Create a Contribution with `Is Code Open Source?` set to `True` and add a repo URL. Then, edit the contribution and change it to `False`. Now, the boolean field has changed its value, but the repo URL still contains the old value. I think it needs to be reset to null. The issue maybe with the update request to Contributions BB as the data in the backend seems to have not changed. Please look into this. Thanks.

Hi, @minump, Maybe my comment wasn't clear enough. Let me add a screenshot below. This is after I set `isCodeOpenSource` to `False.` Please see that the Source code URL still appears on the Contribution view page. It's also present in the JSON. Thanks.

image

image

**Comment by minump** [comment]
> > 
> 
> > Hi, @minump,
> > In the following scenario, there is an issue. Create a Contribution with `Is Code Open Source?` set to `True` and add a repo URL. Then, edit the contribution and change it to `False`. Now, the boolean field has changed its value, but the repo URL still contains the old value. I think it needs to be reset to null. The issue maybe with the update request to Contributions BB as the data in the backend seems to have not changed. Please look into this. Thanks.
> 
> Hi, @minump, Maybe my comment wasn't clear enough. Let me add a screenshot below. This is after I set `isCodeOpenSource` to `False.` Please see that the Source code URL still appears on the Contribution view page. It's also present in the JSON. Thanks.
> 
> image
> 
> image

Sorry, it should be fixed now. Let me know.

**Comment by sandeep-ps** [comment]
Thanks for addressing the issue. I would like to suggest a few items for future improvements:

1. In the Capability view, the source code repo URL label (i.e., the whole line) could be hidden if the value is a null or empty string.
2. Source Repo URL text box needs to be made required, if `Is Code Open Source?` is `yes.

The rest looks good to me. I'm approving this PR. Thanks.

**Review by sandeep-ps — APPROVED** [review]

**Comment by minump** [comment]
> Thanks for addressing the issue. I would like to suggest a few items for future improvements:
> 
> 1. In the Capability view, the source code repo URL label (i.e., the whole line) could be hidden if the value is a null or empty string.
> 2. Source Repo URL text box needs to be made required, if `Is Code Open Source?` is `yes`.
> 
> The rest looks good to me. I'm approving this PR. Thanks.

Sure. Will create 2 tasks for the same and will work on it.

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
