### PR TITLE
1040 header UI changes

### LINKED ISSUE #1040: Header UI changes
UI changes for header in catalog.
Use https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/62b9dbf53ffe5912b9da1f42 as reference

### PR DESCRIPTION
**Pull request by minump**
## Description
The top navigation bar styling is done. See http://localhost:5050/catalog/ top for changes.
Changes reflects zeplin https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/62b9dbf684718712f34fe8d0

**Fixes #1040**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Hi, Minu, I think there are multiple things to be fixed:

1. "Contribute" font color is different from the design.
2. "Contributions Catalog" needs the Block-I logo.
3. Contribute button appears differently on pages other than the home page.
4. Login button margin is slightly smaller than what's needed to keep it at the center
5. Login/logout button font weight needs to be 800 to match the ProximaNova-Bold font.
6. The header height and hello string width need to be updated based on the design.

We need to get the implementation as close as to the design. Please compare the design with the implementation after making these changes. Thanks.

**Comment by minump** [comment]
Converting to draft to fix the changes.

**Comment by minump** [comment]
> Hi, Minu, I think there are multiple things to be fixed:
> 
> 1. "Contribute" font color is different from the design.
> 2. "Contributions Catalog" needs the Block-I logo.
> 3. Contribute button appears differently on pages other than the home page.
> 4. Login button margin is slightly smaller than what's needed to keep it at the center
> 5. Login/logout button font weight needs to be 800 to match the ProximaNova-Bold font.
> 6. The header height and hello string width need to be updated based on the design.
> 
> We need to get the implementation as close as to the design. Please compare the design with the implementation after making these changes. Thanks.

updated changes. Compared to zeplin webpage.

**Comment by sandeep-ps** [comment]
Thanks. 

From the Events Manager design examples, there is a lot more space between the name and the logout button in the top navigation bar. I think it can be reduced. The text "Contributions Catalog" does not vertically align to the center. Otherwise, the current header looks fine to me. Thanks.

The top navigation bar's height might need to be increased to match the design, but that'll also be related to the logo conversation. So, it can probably stay as it is for now.

**Comment by minump** [comment]
Converting to draft to put the Block-I image

**Comment by minump** [comment]
updated styling.
ready for review. @sandeep-ps @bingzhang

**Comment by sandeep-ps** [comment]
The font styles of the Contributions Catalog and log-in (potentially logout text, too) are different on the home page and when the user views one of the Contributions.

Home page: 
image
View Contribution page: 
image

**Comment by sandeep-ps** [comment]
Once the user logs in, the nav bar alignment changes. Please see: 
image

The top nav bar needs to use the available width and position content accordingly. Thanks.

**Comment by minump** [comment]
converting to draft to fix header

**Comment by minump** [comment]
I wasnt able to exactly reproduce the styling errors. But I updated some header stylings (flex divs) and pushed the latest. Let me know if the issue persists.

**Comment by minump** [comment]
Need to add orange hover color for login/logout button.
Need to fix the spacing between different divs in the topnav bar.
Converting to draft.

**Comment by minump** [comment]
Updated header styling.
The login/logout button does not have orange on hover. Let me know if that is needed. Also if I missed anything. @sandeep-ps 
Ready for review.

**Comment by sandeep-ps** [comment]
Hi, Minu,

The style of the text "Contributions Catalog" in the nav bar still looks slightly different on the View Contribution and View Capability pages when compared with the Home page. The rest looks good to me. The login/logout button hover color change could wait for now. Thanks.

**Comment by minump** [comment]
> Hi, Minu,
> 
> The style of the text "Contributions Catalog" in the nav bar still looks slightly different on the View Contribution and View Capability pages when compared with the Home page. The rest looks good to me. The login/logout button hover color change could wait for now. Thanks.

Hi @sandeep-ps 
I had to add the typekit.css style to every page. This made the "Contributions Catalog" title font same for all pages. Somehow to able to replicate the styling without adding the css style for each page.

**Comment by sandeep-ps** [comment]
Thanks, Minu. I think we can look at this again when doing the refactoring, but this looks good now.

**Comment by sandeep-ps** [comment]
Hi, @bingzhang, I'm going to ask Minu to merge this PR as it's been open for a while now. Please review the other PRs that are open in this repo. Thanks.

Hi, @minump, you can proceed with merging this. Thanks.

**Pull request merged**
