### PR TITLE
1066 review page UI changes

### LINKED ISSUE #1066: Review page UI changes
Review page UI changes as per zeplin design.
This is the reviewers page (dropdown and comment divs) in contribution details page.

### PR DESCRIPTION
**Pull request by minump**
## Description
Review block in contribution_details page.
Updated input form fields and button styles.

This Pr is built on top of [contribution/create page PR](https://github.com/rokwire/rokwire-building-blocks-api/pull/1071) for consistency in styles. 

**Fixes #1066**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by sandeep-ps** [comment]
1. The dropdown UI looks different from the design. 
2. When the Review Contribution button is focused (through tab changes), it doesn't match the focus state of buttons in the design. This may apply to other buttons too.

The remaining changes look good to me. Thanks.

**Comment by minump** [comment]
> 

I forgot there was a dropdown menu design. Will customize that.

**Comment by minump** [comment]
> 1. The dropdown UI looks different from the design.
> 2. When the Review Contribution button is focused (through tab changes), it doesn't match the focus state of buttons in the design. This may apply to other buttons too.
> 
> The remaining changes look good to me. Thanks.

Updated dropdown menu design and focus style for buttons.

**Comment by minump** [comment]
@sandeep-ps @bingzhang ready for review.

**Comment by minump** [comment]
> 

Updated styles on hover. Added font-weight bold and border on hover.

**Review by sandeep-ps — APPROVED** [review]
The changes look good to me. Approving.

**Comment by minump** [comment]
Need to change a.button.button{num} to button.button{num} class.

**Comment by minump** [comment]
Need to check if bootstrap select and option can be customized.

**Comment by minump** [comment]
Converting to draft as changes are yet to be made.

**Comment by minump** [comment]
The scope is changed to make the customization of dropdown menu as another issue.
This PR will only deal with the text box change and all other designs except for the dropdown menu customization.

**Comment by minump** [comment]
Customized dropdown removed.

**Comment by minump** [comment]
ready for review @sandeep-ps @bingzhang

**Review by sandeep-ps — APPROVED** [review]
Approving this PR. Thanks.

@bingzhang, please share if you have any feedback. Thanks.

**Comment by minump** [comment]
Merging this PR.
Merging bypassing detect-secrets

**Pull request merged**
