### PR TITLE
1084 card alignment in catalog home page

### LINKED ISSUE #1084: Card alignment in catalog home page
The catalog home page card alignments are changed. the cards are now shifted towards the left. There additional empty space on the right, under the search box.
Screen Shot 2023-02-22 at 11 17 26 AM

Make all text/elements vertically aligned.

Screen Shot 2023-02-22 at 11 46 26 AM

### PR DESCRIPTION
**Pull request by minump**
## Description
Catalog home page card alignment done.
Search bar style changed
Bookshelf image style changed
home page container width increased to fit more cards.

The bookshelf image is shorter than the home page container width. Hence the blank space on the left and right sides.

Screen Shot 2023-03-02 at 12 13 00 PM

**Fixes #1084**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
width : 975 px; margin-left:10px; Try this styling for card container in home page.

**Comment by minump** [comment]
Updated styling of catalog home page. 
Ready for review @sandeep-ps

**Comment by sandeep-ps** [comment]
Could you try without changing the height of the search box? Since that's been standardized across all pages, that may be better.

**Comment by minump** [comment]
> Could you try without changing the height of the search box? (adding a blank line or adding a top margin for the main container) Since that's been standardized across all pages, that may be better.

Updated.
Removed height style css in search bar. Added space (margin-bottom ) before grid cards start.

**Review by sandeep-ps — APPROVED** [review]
Approving. Thanks.

**Comment by minump** [comment]
Merging to develop

**Pull request merged**
